const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'cute',
    imageUrl: 'https://i.ytimg.com/vi/8b3m-8V-qRg/hqdefault.jpg',
    fullness: '67',
    favPose: 'downward facing dog',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat2',
    name: 'nanny',
    disposition: 'rude',
    imageUrl: 'https://pbs.twimg.com/profile_images/893499230853230593/RL_rZ3q2_400x400.jpg',
    fullness: '34',
    favPose: 'Cobra pose',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat3',
    name: 'chilly',
    disposition: 'funny',
    imageUrl: 'https://www.theprairiehomestead.com/wp-content/uploads/2014/11/Oreo-the-Goat.jpg',
    fullness: '12',
    favPose: 'Bridge pose',
    isFainting: false,
    color: 'black',
  },
  {
    id: 'goat4',
    name: 'twilly',
    disposition: 'playful',
    imageUrl: 'https://img.buzzfeed.com/buzzfeed-static/static/enhanced/webdr02/2013/7/8/11/enhanced-buzz-31618-1373297919-21.jpg?downsize=700%3A%2A&output-quality=auto&output-format=auto&output-quality=auto&output-format=auto&downsize=360:*',
    fullness: '99',
    favPose: 'Cat pose',
    isFainting: true,
    color: 'grey',
  },
  {
    id: 'goat5',
    name: 'yanny',
    disposition: 'weird',
    imageUrl: 'http://rmpgclub.com/wp-content/uploads/2018/07/Skipper-3-300x266.jpg',
    fullness: '56',
    favPose: 'Chair pose',
    isFainting: false,
    color: 'black',
  },
];

export default goats;
